name: Deploy and Fix Code

on:
  push:
    branches:
      - main  # 只在推送到 main 分支时触发

jobs:
  lint:
    runs-on: ubuntu-latest  # 运行在 Ubuntu 最新版本的虚拟机上

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出 GitHub 仓库代码

    - name: Set up Node.js
      uses: actions/setup-node@v2  # 配置 Node.js 环境
      with:
        node-version: '14'  # 设置 Node.js 版本

    - name: Install dependencies
      run: npm install  # 安装项目依赖

    - name: Run ESLint
      run: npm run lint --fix  # 运行 ESLint，自动修复格式问题

  deploy:
    needs: lint  # 确保 lint 任务完成后再执行部署
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # 构建项目（如果需要）

    - name: Deploy to Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}  # 登录 Railway
        railway up  # 部署到 Railway
